### ISSUE TITLE
Fix Regexp/Regsub- syntax highlighting breaks when contains quotes

### ISSUE THREAD

**Issue by cPsYcRoW** [zpconn/language-tcl#5]
I have found another issue which is breaking the syntax highlighting, but I am not sure how to fix it.

Here is an offending example:

set bar "This is a an arb line of text"
set foo_list [split [regsub -all -- {(.{0,30})\M\s*} $bar "\\1\uFFFD"] \uFFFD]
set broken_syntax_highlighting [starts $from_quotations_above]

I have narrowed it down to be the quotes within the regsub./regexp. If you escape them with "\" the syntax highlighting behaves nicely again.

Here is another example using regexp:

addproc {regexp {Serial[0-9]{4}$}} "The ID must start with 'Serial'"
set yesno          {"" Yes No}
set passfail         {"" Passed Failed}

If you paste that into a new file and set the grammar to TCL you will see how it breaks.

Perhaps someone could look into modifying the TCL grammar file to handle this for both regsub and regexp?

**Comment by zpconn** [comment]
Thanks for the pull request!
