### ISSUE TITLE
Identifies Tcl files as HTML (Tcl) not Tcl

### ISSUE THREAD

**Issue by mikepyne** [zpconn/language-tcl#7]
Atom Version: 0.146.0
Language Tcl version: 0.1.0

Open a Tcl file; the grammar is selected as "HTML (Tcl)" not "Tcl", so there is no highlighting.

Manually changing the grammar to Tcl means the file is properly highlighted.

**Comment by nickvanderstel** [comment]
Yes, this issue was fixed in master almost a year ago. Can we get a new release?

**Comment by zpconn** [comment]
That release finally went out. :) Sorry for the delay!
